services:
  - type: web
    name: url-shortener
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: "https://oadbqjznmangfwogbbgg.supabase.co "
      - key: IPINFO_API_KEY
        fromSecret: 40a0d17231e700
